using Microsoft.EntityFrameworkCore;
using Arabica.Infrastructure.Veri;
using Testcontainers.Kafka;
using Testcontainers.PostgreSql;
using Xunit;

namespace Arabica.Integration.Tests;

/// <summary>
/// Spins up a throwaway PostgreSQL 16 container and applies the schema. If Docker is unavailable the
/// fixture records the reason and <see cref="Kullanilabilir"/> stays false so dependent tests SKIP.
/// </summary>
public sealed class PostgresFixture : IAsyncLifetime
{
    private PostgreSqlContainer? _container;

    public bool Kullanilabilir { get; private set; }
    public string AtlamaSebebi { get; private set; } = "Docker kullanılamıyor.";
    public string BaglantiDizesi { get; private set; } = string.Empty;

    public async Task InitializeAsync()
    {
        try
        {
            _container = new PostgreSqlBuilder()
                .WithImage("postgres:16")
                .WithDatabase("arabica")
                .Build();
            await _container.StartAsync();
            BaglantiDizesi = _container.GetConnectionString();
            await SemayiUygulaAsync();
            Kullanilabilir = true;
        }
        catch (Exception ex)
        {
            Kullanilabilir = false;
            AtlamaSebebi = $"Docker/Postgres başlatılamadı: {ex.Message}";
        }
    }

    public HistoryDbContext HistoryContext()
        => new(new DbContextOptionsBuilder<HistoryDbContext>().UseNpgsql(BaglantiDizesi).Options);

    public HotDbContext HotContext()
        => new(new DbContextOptionsBuilder<HotDbContext>().UseNpgsql(BaglantiDizesi).Options);

    // TEST CONVENIENCE: mirrors the Liquibase changelogs (db/liquibase). Production schema authority is
    // Liquibase (applied by the docker-compose migration step); here we apply equivalent DDL so the
    // data-access code is tested against exactly the schema the EF model maps to.
    private async Task SemayiUygulaAsync()
    {
        const string ddl = """
            CREATE SCHEMA IF NOT EXISTS hot;
            CREATE SCHEMA IF NOT EXISTS hist;

            CREATE TABLE IF NOT EXISTS hot.sube (
                sube_id               int           PRIMARY KEY,
                ad                    varchar(200)  NOT NULL,
                maksimum_kapasite     int           NOT NULL,
                anlik_musteri_sayisi  int           NOT NULL DEFAULT 0,
                aktif_personel_sayisi int           NOT NULL DEFAULT 0,
                aktif                 boolean       NOT NULL DEFAULT true
            );

            CREATE TABLE IF NOT EXISTS hot.personel (
                personel_id bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sube_id     int           NOT NULL,
                takma_ad    varchar(150)  NOT NULL,
                tip         varchar(20)   NOT NULL,
                aktif       boolean       NOT NULL DEFAULT true
            );

            CREATE TABLE IF NOT EXISTS hist.transfer_emirleri (
                emir_id            bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                kaynak_sube_id     int           NOT NULL,
                hedef_sube_id      int           NOT NULL,
                tip                varchar(20)   NOT NULL,
                adet               int           NOT NULL,
                durum              varchar(20)   NOT NULL,
                red_gerekcesi      varchar(500),
                olusturulma_zamani timestamptz   NOT NULL
            );

            CREATE TABLE IF NOT EXISTS hist.outbox (
                id                uuid          PRIMARY KEY,
                olay_tipi         varchar(100)  NOT NULL,
                anahtar           varchar(100)  NOT NULL,
                icerik            jsonb         NOT NULL,
                olusma_zamani     timestamptz   NOT NULL,
                yayinlandi_mi     boolean       NOT NULL DEFAULT false,
                yayinlanma_zamani timestamptz
            );

            CREATE TABLE IF NOT EXISTS hist.denetim_log (
                id        bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                aktor     varchar(150)  NOT NULL,
                ip_adresi varchar(64)   NOT NULL,
                eylem     varchar(100)  NOT NULL,
                detay     varchar(1000),
                zaman     timestamptz   NOT NULL
            );
            """;

        await using var ctx = HistoryContext();
        await ctx.Database.ExecuteSqlRawAsync(ddl);
    }

    public async Task DisposeAsync()
    {
        if (_container is not null)
            await _container.DisposeAsync();
    }
}

/// <summary>Throwaway Kafka (KRaft) container; skips dependent tests when Docker is unavailable.</summary>
public sealed class KafkaFixture : IAsyncLifetime
{
    private KafkaContainer? _container;

    public bool Kullanilabilir { get; private set; }
    public string AtlamaSebebi { get; private set; } = "Docker kullanılamıyor.";
    public string BootstrapSunuculari { get; private set; } = string.Empty;

    public async Task InitializeAsync()
    {
        try
        {
            _container = new KafkaBuilder().WithImage("confluentinc/cp-kafka:7.6.1").Build();
            await _container.StartAsync();
            BootstrapSunuculari = _container.GetBootstrapAddress();
            Kullanilabilir = true;
        }
        catch (Exception ex)
        {
            Kullanilabilir = false;
            AtlamaSebebi = $"Docker/Kafka başlatılamadı: {ex.Message}";
        }
    }

    public async Task DisposeAsync()
    {
        if (_container is not null)
            await _container.DisposeAsync();
    }
}
